sudo: true
dist: trusty
cache: false
language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install python
install:
- export URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_3025427bf292_key -iv $encrypted_3025427bf292_iv -in assets/server.key.enc -out assets/server.key -d || true'
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- mv force-app/main/test/* force-app/main/default/classes
- pip install bumpversion
- 'if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then cd appscan; make asoc-tool; cd ../; fi'
before_script:
- 'if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then chmod a+x ./appscan/ASOC.sh; fi'
# script:
# - "./install/test-in-scratch-org.sh"
# - 'if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then ./appscan/ASOC.sh; fi'
# after_success:
# - sfdx force:org:delete -u ciorg -p
# after_failure:
# - sfdx force:org:delete -u ciorg -p
before_deploy:
- nvm install 12
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/changelog
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release